name: Update database
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update_database.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Create .env
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env
        working-directory: ./backend
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend
      - name: Update database
        run: npm run import
        working-directory: ./backend